//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mov.Standard.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mov.Standard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string L_IconAdd {
            get {
                return ResourceManager.GetString("L_IconAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string L_IconDelete {
            get {
                return ResourceManager.GetString("L_IconDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string L_IconSearch {
            get {
                return ResourceManager.GetString("L_IconSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mov_Standard_Models_VideoStatus_Delete {
            get {
                return ResourceManager.GetString("Mov_Standard_Models_VideoStatus_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mov_Standard_Models_VideoStatus_Favorite {
            get {
                return ResourceManager.GetString("Mov_Standard_Models_VideoStatus_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mov_Standard_Models_VideoStatus_New {
            get {
                return ResourceManager.GetString("Mov_Standard_Models_VideoStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mov_Standard_Models_VideoStatus_None {
            get {
                return ResourceManager.GetString("Mov_Standard_Models_VideoStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mov_Standard_Models_VideoStatus_See {
            get {
                return ResourceManager.GetString("Mov_Standard_Models_VideoStatus_See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Core_Net_ConnectionStatus_Closed {
            get {
                return ResourceManager.GetString("My_Core_Net_ConnectionStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Core_Net_ConnectionStatus_Exception {
            get {
                return ResourceManager.GetString("My_Core_Net_ConnectionStatus_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Core_Net_ConnectionStatus_Opened {
            get {
                return ResourceManager.GetString("My_Core_Net_ConnectionStatus_Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読取エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Core_Net_ConnectionStatus_ReadingError {
            get {
                return ResourceManager.GetString("My_Core_Net_ConnectionStatus_ReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書込エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Core_Net_ConnectionStatus_WrittingError {
            get {
                return ResourceManager.GetString("My_Core_Net_ConnectionStatus_WrittingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Wpf_Chart_Core_XRangeType_DateTime {
            get {
                return ResourceManager.GetString("My_Wpf_Chart_Core_XRangeType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経過時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Wpf_Chart_Core_XRangeType_TimeSpan {
            get {
                return ResourceManager.GetString("My_Wpf_Chart_Core_XRangeType_TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Wpf_Services_WpfMessageType_Confirm {
            get {
                return ResourceManager.GetString("My_Wpf_Services_WpfMessageType_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Wpf_Services_WpfMessageType_Error {
            get {
                return ResourceManager.GetString("My_Wpf_Services_WpfMessageType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インフォメーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string My_Wpf_Services_WpfMessageType_Info {
            get {
                return ResourceManager.GetString("My_Wpf_Services_WpfMessageType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yy/MM/dd HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string S_Default_DateFormat {
            get {
                return ResourceManager.GetString("S_Default_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイル|.csv|全ファイル|.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string S_Filter_Common_CSV {
            get {
                return ResourceManager.GetString("S_Filter_Common_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV ファイル|.csv|TAB 区切りファイル|.tsv|全ファイル|.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string S_Filter_Common_CSV_TSV {
            get {
                return ResourceManager.GetString("S_Filter_Common_CSV_TSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MP4 ファイル|.mp4|全ファイル|.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string S_Filter_Common_MP4 {
            get {
                return ResourceManager.GetString("S_Filter_Common_MP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mov.Standard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string V_MainTitle {
            get {
                return ResourceManager.GetString("V_MainTitle", resourceCulture);
            }
        }
    }
}
